name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test:ci

      - name: Build
        run: pnpm run build

      - name: Verify package
        run: |
          # Check package.json version matches tag
          PACKAGE_VERSION=v$(node -p "require('./package.json').version")
          TAG_NAME=${GITHUB_REF#refs/tags/}

          if [ "$PACKAGE_VERSION" != "$TAG_NAME" ]; then
            echo "❌ Package version ($PACKAGE_VERSION) doesn't match tag ($TAG_NAME)"
            exit 1
          fi

          echo "✅ Version check passed: $PACKAGE_VERSION"

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body: |
            ## 🚀 Published to npm

            Install with:
            ```bash
            npm install @kimsungwhee/apple-docs-mcp
            ```

            ## 📦 What's included
            - Complete WWDC video data (1260+ videos)
            - 18 MCP tools for Apple documentation
            - Full TypeScript support
            - Bundled data (no external dependencies)

            ## 📝 Changelog
            See the [full changelog](https://github.com/kimsungwhee/apple-docs-mcp/blob/main/CHANGELOG.md)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}